opencost/opencost-helm-chart

Chart.yaml
README.md
templates/clusterrole.yaml
templates/clusterrolebinding.yaml
templates/deployment.yaml
templates/namespace.yaml
templates/service.yaml
templates/serviceaccount.yaml
values.yaml

Split out https://github.com/opencost/opencost/tree/develop/kubernetes/opencost.yaml and added a few initial template values. 
Should produce the same result `opencost.yaml`. 
Signed-off-by: Liam Newman <liam@verta.ai>

Initial port from opencost.yaml

---

templates/deployment.yaml

The extra `}` results in a templating failure:
```
Error: YAML parse error on opencost/templates/deployment.yaml: error converting YAML to JSON: yaml: line 47: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 47: did not find expected key
YAML parse error on opencost/templates/deployment.yaml
```

Fix invalid helm template in deployment.yaml

---

charts/opencost/templates/deployment.yaml
charts/opencost/templates/secret.yaml
charts/opencost/values.yaml

- Adding ability to annotate pods
- Making secret creation optional based on the secret values
- Adding option to add bearer token for prometheus
- Updated values.yaml accordingly

add pod annotation and make secret object optional

---

charts/opencost/Chart.yaml

I merged #24 without bumping the semver which resulted in the publish artifact stage to fail due to conflicting tag names. 
This change bumps to `1.2.0`, which should reflect the minor changes added.

chore(chart): Bump version a minor number for #24

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml

Fixing the incorrect location for the pod annotation in https://github.com/opencost/opencost-helm-chart/pull/24 and also bumped the version to avoid the version issues.
@Pokom I noticed that issue while deploying, so apologies for the back and forth, can you take a look please?

fix the location of annotations for pods

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml

I use GitOps tool like FluxCD or ArgoCD. So, the code gets versioned.
So I needed to put an API key of GCP... but the `opencost.exporter.cloudProviderApiKey` is vulnerable. My security scanner argues about it.
Usually we could use a Kubernetes Secret that can be read from an Env. Like this
```
opencost:
exporter:
defaultClusterId: 'default-cluster'
env:
- name: CLOUD_PROVIDER_API_KEY
valueFrom:
secretKeyRef:
name: some-safety-secret
key: key
```
It's fine. It's standard. So I'm sure the OpenCost Helm Chart can support it too.
Ah! I tested it with no problem, you can do so.
```
helm template --dry-run .
```
Please, I need this fix/feature. Can you help me out?

fix,chore: Plain text of API key

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/README.md.gotmpl
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

There was a mismatch between badges (AppVersion: 1.9.8) and version installed (latest tag).
While I fixed this, I documented every helm parameter via the required comments above each value. Let me know if I should split it into multiple PRs.
Resolves #23

feat: Install pinned version rather than latest tag

---

.github/configs/ct.yaml
.github/configs/lintconf.yaml
.github/workflows/helm-test.yml

I ([argo-helm](https://github.com/argoproj/argo-helm) maintainer) would like to share our workflow for CI testing.
Resolves #30
Tested it on my fork repo:
The code is mostly based on the howto/README of the [helm/chart-testing-action](https://github.com/helm/chart-testing-action).
The only thing we (at argo-helm) recently adapted is to remove the deprecated `echo "::set-output name=changed::true"` with `echo "changed=true" >> $GITHUB_STATE`.
Deprecation and howto fix is documented in the GitHub blog post: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples

chore: Adapt workflow to common helm testing

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Fixes https://github.com/opencost/opencost-helm-chart/issues/33
Default remains 1 replica

Support configurable number of replicas on the deployment

---

.github/workflows/helm-test.yml

Hi again
My last PR (#35) contained a bug which was also present in my main repository over there: [argoproj/argo-helm](https://github.com/argoproj/argo-helm).
So this one here is a "backport" of our fix:
- https://github.com/argoproj/argo-helm/pull/1904
/cc: @mattray @Pokom @toscott

fix: Last PR (#35) contained a bug, replace GITHUB_STATE -> GITHUB_OUTPUT

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

This PR adds the ability to define the securityContext on both container- and pod-level.
/cc: @toscott @mattray @Pokom

feat: Add ability to define securityContexts and podSecurityContext

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Follow-up of discussion in PR:
- #38
> Just as a note to anyone leveraging this later, the UI container crashes if readOnlyRootFilesystem is true as it needs to write to tmp space.
> 
> [emerg] 1#1: mkdir() "/tmp/proxy_temp" failed (30: Read-only file system)
>
> _Source: @toscott , https://github.com/opencost/opencost-helm-chart/pull/38#discussion_r1138037333_

feat: Add ability to inject extraVolumeMounts into UI container

---

charts/opencost/README.md
charts/opencost/values.yaml

Replace the (probably internal) Alto's Mimir endpoint to something more general.

fix: remove Alto mimir endpoint

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/deployment.yaml
charts/opencost/templates/secret.yaml
charts/opencost/values.yaml

Specifically, it allows you to override the secret name, the keys for the username, password, and/or bearer token inside that secret. Just like before, the secret is created values for `username`, `password`, or `bearer_token` are set, and the secret will not be created if those values are not set.
This also updates the deployment to reference the secret with named keys, even if the secret has not been created.
Fixes #75

Add some options for the prometheus secret so you can use an existing secret

---

charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

The PR fixes liveness and readiness probes:
- Removed duplicated `readinessProbe` for exporter container
- Renamed `opencost.exporter.redinessProbe` property to `opencost.exporter.readinessProbe`
- `failureThreshold` field uses `failureThreshold` property value instead of `periodSeconds`
- Set `failureThreshold` to default value `3` instead of super high `200`

Fix liveness and readiness probes

---

charts/opencost/templates/clusterrole.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/pvc.yaml
charts/opencost/templates/secret.yaml
charts/opencost/templates/service.yaml
charts/opencost/templates/serviceaccount.yaml

The PR removes redundant `namespace` from the chart templates.
Helm creates Kubernetes resources (Deployment, ConfigMap, Service, Ingress etc.) in the same namespace where the chart installed, i.e. `.Release.Namespace` is used by default. So there is no reason to set namespace explicitly and it can be removed to keep code cleaner.

Remove redundant namespace

---

.github/configs/cr.yaml

* Enables release note generation via an [option](https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages) provided by chart-releaser. chart-releaser uses GitHub's feature for automatic release note generation ([docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)).
* Current release notes provided in the release are unusable with tools like [Renovate](https://github.com/renovatebot/renovate).

chore(github): Generate release notes

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/clusterrole.yaml
charts/opencost/templates/clusterrolebinding.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/ingress.yaml
charts/opencost/templates/pvc.yaml
charts/opencost/templates/secret.yaml
charts/opencost/templates/service.yaml
charts/opencost/templates/serviceaccount.yaml
charts/opencost/templates/servicemonitor.yaml
charts/opencost/values.yaml

The PR reformats chart templates to one style with more readable blocks and indents to improve code readability.
Fixed duplicated `volumeMounts` in main container.
Similar changes: https://github.com/apache/airflow/pull/29917 https://github.com/apache/airflow/pull/29941 https://github.com/apache/airflow/pull/30312 https://github.com/minio/minio/pull/16947 https://github.com/apache/superset/pull/23681

Reformat chart templates

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/clusterrole.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

The PR makes `imagePullPolicy` properties configurable with default value `IfNotPresent` for `exporter` and `ui` containers.
The PR includes minor README changes rendered by `helm-docs` run.

Make imagePullPolicy properties configurable

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

- Add thanos support 
- https://github.com/opencost/opencost/blob/develop/pkg/env/costmodelenv.go#L49-L52
- It doesn't install thanos. Thanos has to be installed first.

feat: Support thanos integration

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/values.yaml

Increased default values `initialDelaySeconds` for `livenessProbe` and `readinessProbe`. Related to #73

increased readiness and liveness probe delay to 120

---

charts/opencost/Chart.yaml
charts/opencost/README.md

1.106.2 was released, it's just a bump for CVEs in the underlying containers.

Bump to OpenCost 1.106.2, a minor release.

---

charts/opencost/templates/deployment.yaml
charts/opencost/templates/secret.yaml

The `cloudProviderApiKey` value should be stored in a secret and referenced from this secret than exposing it. IT Sec people would thank for this.

Store and reference cloud API key in secret

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

There are scenarios where the pod can get scraped twice by the ServiceMonitor. This will leave duplicate series in prometheus that may lead to many-to-many queries causing broken grafana dashboards.
With this change updateStrategy can be changed to Recreate for those cases.
Example error message
> Status: 500. Message: execution: found duplicate series for the match group {instance_type="m5a.8xlarge", node="ip-10-1-120-2.ec2.internal"} on the right hand-side of the operation: [{container="opencost", endpoint="http", instance="10.1.116.161:9003", instance_type="m5a.8xlarge", job="opencost", label_beta_kubernetes_io_arch="amd64", label_beta_kubernetes_io_instance_type="m5a.8xlarge", label_beta_kubernetes_io_os="linux", label_failure_domain_beta_kubernetes_io_region="us-east-1", …

Make deployment updateStrategy variable.

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/configmap-custom-pricing.yaml
charts/opencost/values.yaml

What
Allow overriding the pricing provider type in the custom pricing configuration file. 
Why
This allows us to provide the costModels for any provider directly through the configmap in the helm chart. For example, the aws provider and spot feed information could be configured with a values override that looks like this:
```
opencost:
customPricing:
enabled: true
provider: aws    
costModel:
awsSpotDataRegion: us-east-2
awsSpotDataBucket: my-spot-bucket
awsSpotDataPrefix: spot_pricing_prefix
```
My hope is this simplifies Cost Model configuration for all providers by providing a straightforward path to configure it directly through the helm chart.

Allow overriding the pricing provider type

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/values.yaml

During testing for the Cloud Costs feature the default repository was set to gcr.io, but that's not where builds are published by default. Restores back to the previous defaults and bumps for the new 1.107.0 release

1.107.0 release and revert to standard quay.io image repositories

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/configmap-custom-pricing.yaml

Respect the configured provider to name the config file accordingly, so OpenCost can fetch spot data from s3.
RESOLVES: #129

Provider related custom pricing config file name

---

charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

In order to use [tilt](tilt.dev), OpenCost's helm chart needs to support a value that is the 'fullImageName' of a docker image, to increase flexibility for development environments - particularly the case of images going to a locally run cluster (like kind or minikube) and do not need to be pushed to docker.hub or another image repository.
This is also designed to align with an identical feature in the Kubecost helm charts.

add in fullImageName to support development envs

---

README.md
charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/README.md.gotmpl
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/clusterrolebinding.yaml
charts/opencost/templates/configmap-custom-pricing.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/ingress.yaml
charts/opencost/templates/networkpolicy.yaml
charts/opencost/templates/pvc.yaml
charts/opencost/templates/secret.yaml
charts/opencost/templates/service.yaml
charts/opencost/templates/serviceaccount.yaml
charts/opencost/values.yaml

Adding parameter `namespaceOverride` as requests on #161.
When using `--set namespaceOverride=<namespace>`, it is required to pre-create the namespace.
Improved the README as well.
Log of the test:
```
% k create ns override
% helm install opencost-override ./charts/opencost --set namespaceOverride=override
NAME: opencost-override
LAST DEPLOYED: Thu Jan 11 14:49:52 2024
NAMESPACE: default  <-----------
STATUS: deployed
REVISION: 1
TEST SUITE: None
% helm install opencost-vanilla ./charts/opencost --namespace=vanilla --create-namespace 
NAME: opencost-vanilla
LAST DEPLOYED: Thu Jan 11 14:50:14 2024
NAMESPACE: vanilla
STATUS: deployed
REVISION: 1
TEST SUITE: None
% k get pod -n override -w
NAME                                 READY   STATUS    RESTARTS   AGE …
```

feat: adding namespace override

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
Kubernetes Docs: 
>The kubelet uses startup probes to know when a container application has started. If such a probe is configured, liveness and readiness probes do not start until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding them getting killed by the kubelet before they are up and running.

feat: `startupProbe` to avoid a long initial delay seconds for liveness probe

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

I looked deeper into the helm chart and I noticed two things:
1. IMHO the section name `opencostMetrics` does not fit well. Therefore I would suggest to set it to `opencost.metrics.kubeStateMetrics`
2. It is not common in this helm chart to use the `default` function, which is used in the [cost-analyzer-helm-chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/). 
My suggestion in this draft is to set only the settings configured by the user. In other words, not to set default values at all. Example configuration:
```YAML
kubeStateMetrics:
emitPodAnnotations: ""
emitNamespaceAnnotations: ""
emitKsmV1Metrics: "" 
emitKsmV1MetricsOnly: ""
```
If default values are preferred, I currently see two options:
1. Use the same approach as the cost-analyzer. Example …

feat: add ability to set KSM settings via helm chart values

---

charts/opencost/Chart.yaml
charts/opencost/templates/configmap-metrics-config.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/networkpolicy.yaml
charts/opencost/values.yaml

* Support extra egress rules. This is useful for environments that have default deny and we need to specify that OpenCost can download pricing data from `aws`.
* Adds support to be able to specify `disabledMetrics` via `metrics-config`. This is useful when you only want to emit KSM v2 metrics and need to suppress duplicate metrics.

Support for extra egress rules and metricConfig ConfigMap

---

.github/workflows/publish.yml

Use latest version of sigstore/cosign-installer to fix publisher pipeline. There was a breaking change in version [v3.0.0](https://github.com/sigstore/cosign-installer/releases/tag/v3.0.0).

fix(workflows): bump versions for publishing pipeline

---

README.md
charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/README.md.gotmpl

- Badges of README.md are now listed line by line for a better overview
- Added org badge to the README.md
- Added repo badges to the charts/opencost/README.md

feat: add ArtifactHub badges to README.md

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Discussed with @mattray. This should provide a better usability.

chore(kubeStateMetrics): make it clear that the keys of kubeStateMetrics only accept booleans for the values

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Hello, with current approach prometheus username and password should be added to values.yml, and helm create secret based on those values. But in case when secret already exist in kubernetes there is no way to use it with opencost helm cahrt. This PR allowing to use existing secrets

Option to use existing kubernetes secret 

---

charts/opencost/Chart.yaml
charts/opencost/templates/configmap-metrics-config.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

CONFIG_PATH is a single directory where both the custom pricing (`aws.json`) and `metrics.json` need to exist.
The only way to map multiple ConfigMaps into a single folder is to use subPath, so both `ConfigMap` volume mounts now use `subPath`.
This also unifies the way the names of the custom pricing and metrics configmap names are configured to follow the way the custom pricing one works.
This is a fix for the original change in https://github.com/opencost/opencost-helm-chart/pull/183

Fix support for disabledMetrics configmap

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml

This fixes the bug I reported in https://github.com/opencost/opencost-helm-chart/issues/205, where the `CONFIG_PATH` directory is mounted as a file instead of as a directory:
```
~ $ ls /tmp/custom-config -l
-rw-r--r--    1 root     root           299 May 15 10:27 /tmp/custom-config
~ $ cat /tmp/custom-config 
{
"CPU": "1.25",
"GPU": "0.95",
"RAM": "0.5",
"description": "Modified pricing configuration.",
"internetNetworkEgress": "0.12",
"regionNetworkEgress": "0.01",
"spotCPU": "0.006655",
"spotRAM": "0.000892",
"storage": "0.25",
"zoneNetworkEgress": "0.01",
"provider" : "custom"
}~ $
```
This causes the pod to fail with:
```
opencost 2024-05-15T10:27:58.127897889Z ERR error accessing cloud provider configuration: stat /tmp/custom-config/default.json: not a directory
```

Fix error when loading custom pricing configuration file 

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml

A previous MR switched to using subpaths because we want to mount two different ConfigMaps into the same folder, however you have to include the filename in the `mountPath` and the `subPath` for this to work properly.
Fixes #205

Fixes missing inclusion of subpath for the mount path

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Enabled and test: 
```
$ curl -G http://localhost:9003/assets/carbon -d window=7d | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1508  100  1508    0     0   3441      0 --:--:-- --:--:-- --:--:--  3435
{
"code": 200,
"status": "success",
"data": {
"GCP/__undefined__/mattray-opencost/Compute/gke-opencost/Node/Kubernetes/gke-opencost-1-default-pool-e40c4801-57g6/gke-opencost-1-default-pool-e40c4801-57g6": {
"co2e": 0.006030856875453464
},
"GCP/__undefined__/mattray-opencost/Compute/gke-opencost/Node/Kubernetes/gke-opencost-1-default-pool-e40c4801-gtyn/gke-opencost-1-default-pool-e40c4801-gtyn": {
"co2e": 0.006030856875453464
},
"GCP/__undefined__/mattray-opencost/Compute/gke-opencost/Node/Kubernetes/gke-op …
```

Add support for enabling the Carbon Cost API

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

feat: include image digest to prevent supply chain issues

---

.github/workflows/helm-test.yml
.github/workflows/publish.yml
.github/workflows/stale.yml

uses SHAs for pinning third party action workflows.
Fixes #219

fix helm chart publish workflow

---

charts/opencost/Chart.yaml

The CI is failing because a PR was merged but the version of the chart was not updated.
This should fix the CI.

Update version to fix CI

---

.github/workflows/publish.yml

Fix, so that we get the following ArtifactHub badges for the OCI repository: 
- Verified publisher
- Official
Repo: https://artifacthub.io/packages/helm/opencost-oci/opencost

fix(artifacthub): push artifacthub-repo.yml file to oci repository (artifacthub/hub#3919)

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/values.yaml

Signed-off-by: Cliff Colvin <ccolvin@kubecost.com>

bump 1.112.1

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

- Return `@` before `sha256` in `opencost.image.tag` and `opencost.ui.image.tag`
- Fix `sha256` hashes
This fixes #233

Fix typo in image.tag default values

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

Signed-off-by: Cliff Colvin <ccolvin@kubecost.com>

bump opencost version to 1.113.0

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/clusterrolebinding.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/monitoring-role-binding-template.yaml
charts/opencost/templates/monitoring-role-template.yaml
charts/opencost/values.yaml

* Add `kubeRBACProxy` property to set `KUBE_RBAC_PROXY_ENABLED` as true in the env var of the container.
* `createPrometheusClusterRoleBinding` property to create cluster role binding to grant required permissions to the serviceaccount to query prometheus with [kube-rbac-proxy](https://catalog.redhat.com/software/containers/rhacm2/kube-rbac-proxy-rhel8/611d4320eb34b73652492bb8) enabled. 
* Add the role binding to grant permissions this external prometheus to scrape metrics from kubecost. 
* Add fail if both `kubeRBACProxy` and `BearerToken` property cannot be set together.
Testing:
deployed opencost in openshift cluster using in cluster prometheus. We were able to query the prometheus.
```sh
2024-12-06T19:03:40.832625335Z INF Prometheus/Thanos Client Max Concurrency set to 5 …
```

Add kubeRBACProxy property to support querying in cluster prometheus in openshift

---

charts/opencost/Chart.yaml
charts/opencost/templates/clusterrole.yaml
charts/opencost/templates/clusterrolebinding.yaml

clusterrole.yaml: add if condition for .Values.rbac.enabled, like on the clusterrolebinding
fix #241

clusterrole.yaml: add if condition for .Values.rbac.enabled

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl
charts/opencost/values.yaml

By adding clusterName to values, you can install OpenCost in clusters with names other than cluster.local and connect to Prometheus correctly.
This fixes #235

Add clsuterName to support clusters with non-default names

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

increments opencost to 1.114 version, bumps app version as well

bump OC to 1.114

---

charts/opencost/README.md

Addresses issue https://github.com/opencost/opencost-helm-chart/issues/246
Though this fixes only the latest readme, certain version readmes still remain outdated.

update chart version and app version

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

Setting CPU limits is no longer recommended, see
https://home.robusta.dev/blog/stop-using-cpu-limits

charts/opencost/values.yaml: remove CPU limits

---

charts/opencost/Chart.yaml
charts/opencost/templates/route.yaml
charts/opencost/values.yaml

This is **not** meant as a PR ready to merge. I just wanted to start a discussion, if the functionality to create an OpenShift route via the helm chart would be something worth adding.
I know the chart can create an ingress, but if you want to put OpenCost behind a oauth-proxy, you need to put the route name into an annotation on the `serviceAccount`. And if the route is being created from an ingress automatically, its name contains a random hash...

allow creating an OpenShift route

---

.github/workflows/publish.yml
charts/opencost/README.md

Fixes: https://github.com/opencost/opencost-helm-chart/issues/258
Removed the `CR_RELEASE_NAME_TEMPLATE` having `version-helm` as with multiple charts we can having conflicts.
removing it would default to `name-version`
Added `CR_SKIP_EXISTING` to skip existing charts that did not have a version bump similar to https://github.com/helm/chart-releaser/pull/111#issue-830518351

Fix: Chart release script

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/configmap-frontend.yaml
charts/opencost/values.yaml

Currently errors are thrown when the nginx is unable to bind to an IPv6 address. This needs to be disabled for clusters where IPv6 is disabled.
I've added a flag that defaults to true for this setting so it's backwards compatibly but allows disabling the IPv6 requirement.

Add opencost.ui.useIPv6 feature flag

---

charts/opencost-parquet-exporter/Chart.yaml
charts/opencost-parquet-exporter/templates/_helpers.tpl
charts/opencost-parquet-exporter/templates/cronjob.yaml
charts/opencost-parquet-exporter/values.yaml

This PR aims at using the appVersion defined in Chart.yaml as the default container image rather than using "main". (Same as the opencost helm chart).
It also sets the appVersion to 0.2.1, as it is the [latest release](https://github.com/opencost/opencost-parquet-exporter/releases/tag/v0.2.1) of the exporter
Close #259

feat(parquet-exporter): use appVersion in Chart.yaml as default tag for container image

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

It's best practice to disable automounting the service account tokens. In heavily audited environments there is often an admission controller preventing pods starting that have automountServiceAccountToken enabled and the same with service accounts. They require it to be explicitly set to false.
This change makes that behaviour configurable per SA and pod.

feat(sec) - customize service account mounting

---

README.md

Looks a good practice to install plugins and an easier one-liner to install unittest instead of visiting the unittest URL for more documentation.

(doc) update readme to easily install unittest

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/pdb.yaml
charts/opencost/values.yaml

This PR intends to allow users to make OpenCost highly available by configuring a Pod Disruption Budget (affinity and replicas already present).
Fix for issue: https://github.com/opencost/opencost-helm-chart/issues/286

Add support for Pod Disruption Budget

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

We can run opencost in two modes, in agent mode only metrics are emitted and in the default mode it provides all the cost attribution api's in addition to cost metrics. But the helm chart doesn't provide an option to run opencost in `agent` mode. This PR adds that option.

add option to override the default container command

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/configmap-frontend.yaml
charts/opencost/values.yaml

This PR depends directly on opencost-ui PR  [#106](https://github.com/opencost/opencost-ui/pull/106).
It enables customizing the path used to serve the OpenCost web UI.
This change also addresses some previously reported issues:
- https://github.com/opencost/opencost-helm-chart/issues/238
- https://github.com/opencost/opencost-helm-chart/issues/148

Add uiPath configuration for OpenCost UI

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/_helpers.tpl
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Resolves: https://github.com/opencost/opencost-helm-chart/issues/302
Added Helm value configs to allow users to mount customer certs to opencost container.
Reference taken from: 
https://github.com/kubecost/kubecost/pull/3763
https://jfrog.com/help/r/artifactory-how-to-add-custom-ssl-certificates-to-an-artifactory-pod-using-helm-charts/artifactory-how-to-add-custom-ssl-certificates-to-an-artifactory-pod-using-helm-charts

Add configs to mount custom ca certs to opencost container
