.github/workflows/helm-test.yml
Chart.yaml
values.yaml

After #1 is merged, we can try this to ensure future PRs have at least basic chart testing.
Copied from https://github.com/helm/chart-testing-action#example-workflow 
Signed-off-by: Liam Newman <96086065+liam-verta@users.noreply.github.com>

Add helm test action

---

Chart.yaml
README.md
templates/deployment.yaml
templates/service.yaml
templates/serviceaccount.yaml
values.yaml

Match the behavior from https://www.opencost.io/docs/install
Fixes https://github.com/opencost/opencost-helm-chart/issues/5

Deploy to the "opencost" namespace by default

---

templates/_helpers.tpl

Signed-off-by: Matt Ray <github@mattray.dev>

PROMETHEUS_SERVER_ENDPOINT needs to prefix with "http://" and include ".svc"

---

charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Hello, 
We are running OpenCost on AKS and the ability to mount volumes would be extremely helpful. As of now, we are modifying the OpenCost chart, but it would be very appreciated if it could be added to an official chart. I believe it will help many users to solve their particular use cases.

Extravolumes

---

README.md
charts/opencost/Chart.yaml

Added a feature, not a bugfix, so bumping minor version.

Bump version to 1.1.0 to be more strict on SemVer following.

---

README.md

He's been active in managing PRs and answering questions in #opencost Slack, I welcome additional maintainers.

Proposal to make Tony Scott a maintainer.

---

charts/opencost/Chart.yaml
charts/opencost/templates/ingress.yaml
charts/opencost/values.yaml

feat: add Ingress for opencost UI

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

feat: Add podLabels for opencost's pods

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

feat: add priorityClassName

---

charts/opencost/Chart.yaml

Version bump to 1.102.0

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/clusterrolebinding.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/service.yaml
charts/opencost/templates/serviceaccount.yaml
charts/opencost/values.yaml

Merging in all three open pull requests and bumping version to 1.12.0

Bulk merge

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/pvc.yaml
charts/opencost/templates/secret.yaml
charts/opencost/values.yaml

add CSV exporter PersistentVolume and enable AWS s3 storage

add CSV exporter pvc

---

charts/opencost/Chart.yaml

This fixes the broken test from commit 6ed2eb4

fix: increase chart version with Alto's prometheus endpoint removal

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/secret.yaml

The following will be resolved
https://github.com/opencost/opencost-helm-chart/issues/70

fix: Secret is created by adding aws settings

---

charts/opencost/Chart.yaml
charts/opencost/README.md

Tested against EKS and local cluster.

Update to 1.104.0 release and minor README cleanup.

---

charts/opencost/Chart.yaml
charts/opencost/README.md

Fixes https://github.com/opencost/opencost/issues/2007

Bump the version to 1.104.4.

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/templates/secret.yaml

Roll up https://github.com/opencost/opencost-helm-chart/pull/88 and add the version bump

Bshramin patch 1

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

Added service account name field in `values.yaml`

Added name field in service account

---

.github/configs/stale.yaml
.github/workflows/stale.yml

https://github.com/marketplace/actions/close-stale-issues

Add support for Close Stale Issues GitHub Action

---

charts/opencost/Chart.yaml
charts/opencost/README.md

Update the default to the latest.

Upgrade to 1.105.2

---

charts/opencost/README.md

The helm chart readme images are out of sync with the actual versions.

fix: outdated version images

---

charts/opencost/Chart.yaml
charts/opencost/templates/_helpers.tpl

- my team needs to use the fully qualified url including `svc.cluster.local`
- small comment fixes

Proposal: fully qualify prom internal url and minor comment updates

---

charts/opencost/Chart.yaml
charts/opencost/README.md

Just published latest release
https://github.com/opencost/opencost/releases/tag/v1.106.4

1.106.4 release is current

---

charts/opencost/templates/deployment.yaml
charts/opencost/values.yaml

Add the possibility to add environment variables to the opencost-ui pod

Add optional environment variables to opencost-ui container

---

charts/opencost/Chart.yaml
charts/opencost/templates/deployment.yaml
charts/opencost/templates/install-plugins.yaml
charts/opencost/templates/plugins-config.yaml
charts/opencost/values.yaml

adds plugin support for the OC helm chart. increments chart version to 1.31

implement plugin support in helm chart

---

.github/workflows/helm-test.yml
.github/workflows/publish.yml

GHA were failing on publish, let's see if this straightens it out.

Bump all the GitHub Action dependencies

---

.github/workflows/publish.yml
artifacthub-repo.yml

issue reference: https://github.com/artifacthub/hub/issues/3919
docs: https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support

feat(artifacthub): push artifacthub-repo.yml file to oci repository

---

charts/opencost/values.yaml

A little helper text about the secret env variable PROMETHEUS_HEADER_X_SCOPE_ORGID

docs: add comment about direct access to mimir

---

.github/workflows/publish.yml

we don't need experimental anymore, we are using latest cosign here.
// cc @mattray (ref: https://github.com/opencost/opencost-helm-chart/actions/runs/10159305960/job/28093258206)

fix cosign signing issue

---

charts/opencost/Chart.yaml
charts/opencost/README.md
charts/opencost/values.yaml

Signed-off-by: Cliff Colvin <ccolvin@kubecost.com>

bump 1.112.0

---

README.md
charts/opencost/Chart.yaml

As voted on in the community meeting on 1/23, we are adding @mittal-ishaan and @jessegoodier as maintainers! Welcome! 
Also, removing Matt Ray who is no longer maintaining the helm chart

Welcome Ishaan and Jesse

---

README.md

Updating reference of chart publish workflow as current is not showing real status

Updating chart badge

---

.github/configs/ct.yaml
.github/workflows/helm-test.yml
charts/opencost/Chart.yaml
charts/opencost/values.yaml

Signed-off-by: Ishaan Mittal <ishaanmittal123@gmail.com>

Bump OC to 1.115.0

---

charts/opencost/Chart.yaml
charts/opencost/values.yaml

Signed-off-by: Ishaan Mittal <ishaanmittal123@gmail.com>

Update opencost ui 1.115.0 image

---

.github/workflows/stale.yml

tweak params
